import Head from 'next/head';
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillGithub, AiFillLinkedin, AiFillCode, AiOutlineLink} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/logo.jpg";
import trainerbook from "../public/trainerbookLogo.png";
import peggle from "../public/peggleLogo.png";
import covidApp from "../public/covidAppLogo.png";
import {useState} from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode?"dark":""}>
      <Head>
        <title >Achille Cannavale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 font-mono  '>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='sm:text-xl text-gray-800 dark:text-gray-100 text-l '>Achille Cannavale</h1>
          <ul className='flex items-center'>
            <li><BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)} className='cursor-pointer tet-2x text-gray-800 dark:text-gray-100'></BsFillMoonStarsFill></li>
            <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 font-bold'  href="https://drive.google.com/file/d/1_Qq1owh1FwfVfDHIyFi5aS6MGZFMfA2C/view?usp=sharing">Resume</a></li>
          </ul>
          </nav>
        <div className='text-center p-5'>
          <h2 className='text-5xl  py-2 text-teal-600 font-medium md:text-6xl'>Achille Cannavale</h2>
          <h3 className='tet-2xl py-2 md:text-3xl dark:text-gray-300 font-bold'>CS Engineering Student | Developer</h3>
          <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-100'>
          I am a Computer Science Engineering student based in Italy. I have a profound interest in Full Stack Development, Machine and Deep Learning, and Cyber Security.
          </p>
        </div>
        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
          <a href="https://www.linkedin.com/in/achille-cannavale/"><AiFillLinkedin></AiFillLinkedin></a>
          <a href='https://github.com/Achille1912'><AiFillGithub></AiFillGithub></a>
          <a href="https://stackoverflow.com/users/14033055/achille"><AiFillCode></AiFillCode></a>
        </div>
        <center>
        <div className='relative rounded-full w-auto h-auto sm:h-80 sm:w-80 mt-20 overflow-hidden  '>
          <Image src={deved} layout="fill" ></Image>
        </div>
        </center>
        </section>
        <section>
          <div >
            <h3 className='text-3xl py-5 text-gray-800 dark:text-gray-100 font-bold'>About Me</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-100'>
            I am particular interest in the world of software development and artificial intelligence.
            I have recently started to independently study the development on the Unity game engine, and above all the development of multi-platform mobile applications through the Flutter framework.
            </p>
          </div>
          <h3 className='text-3xl py-5 text-gray-800 dark:text-gray-100 font-bold'>Projects</h3>
          <div className='lg:grid gap-4 grid-cols-3 grid-rows-1'>
          
          <div className="text-center shadow-slate-900 shadow-lg p-5 rounded-xl my-10 dark:bg-gray-500 dark:shadow-slate-400 ">
          <a  href="https://trainerbook.it/"><AiOutlineLink className=' absolute '></AiOutlineLink></a>
            <center ><Image  src={trainerbook} width={100} height={100} /></center>
            
              <h3 className="text-lg font-bold pt-8 pb-2 text-gray-800 ">
                Trainerbook
              </h3>
              <p className='text-gray-800 py-1'>
                I created the Trainerbook mobile application for Android devices, with the help of the Flutter Framework, using the object-oriented programming paradigm.
                In this project I collaborated with other developers, through the Git system.
              </p>
              <p className='text-gray-800 py-1 text-sm'>Flutter</p>
              <p className='text-gray-800 py-1 text-sm'>Dart</p>
              <p className='text-gray-800 py-1 text-sm'>Git</p>
              
            </div>
            <div className="text-center shadow-slate-900 shadow-lg p-5 rounded-xl my-10 dark:bg-gray-500 dark:shadow-slate-400 ">
            <a  href="https://github.com/Achille1912/PeggleBox2D_"><AiOutlineLink className=' absolute '></AiOutlineLink></a>
            <center><Image src={peggle} width={100} height={100} /></center>
              <h3 className="text-lg font-bold pt-8 pb-2 text-gray-800">
                PeggleBox2D
              </h3>
              <p className='py-2 text-gray-800'>PeggleBox2D is an University Project which consists of the clone of the Peggle game, made with Qt and the Box2D library.</p>
              <p className='text-gray-800 py-1 text-sm'>C++</p>
              <p className='text-gray-800 py-1 text-sm'>OOP</p>
              <p className='text-gray-800 py-1 text-sm'>QT</p>
              <p className='text-gray-800 py-1 text-sm'>Artificial Intelligence</p>
            </div>
            <div className="text-center shadow-slate-900 shadow-lg p-5 rounded-xl my-10 dark:bg-gray-500 dark:shadow-slate-400 ">
            <a  href="https://github.com/Achille1912/CovidApp-flutter"><AiOutlineLink className=' absolute '></AiOutlineLink></a>
            <center><Image src={covidApp} width={100} height={100} /></center>
              <h3 className="text-lg font-bold pt-8 pb-2 text-gray-800">
                CovidApp
              </h3>
              <p className='py-2 text-gray-800'>CovidApp is an application made in Flutter that keeps you informed on cases of infections and daily and total deaths in the world or in your country, through a Geolocation system, of Covid19.</p>
              <p className='text-gray-800 py-1 text-sm'>Flutter</p>
              <p className='text-gray-800 py-1 text-sm'>Dart</p>
              <p className='text-gray-800 py-1 text-sm'>Api</p>
            </div>
          </div>
        </section>
        <footer className='text-center mb-5'>Built and designed by Me.
All rights reserved. ©</footer>
      </main>
    </div>
  )
}
