import Head from 'next/head';
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/logo.jpg";
import {useState} from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode?"dark":""}>
      <Head>
        <title>Achille Cannavale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl'>Achille Cannavale</h1>
          <ul className='flex items-center'>
            <li><BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)} className='cursor-pointer tet-2x dark:text-gray-100'></BsFillMoonStarsFill></li>
            <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 ' href="#">Resume</a></li>
          </ul>
          </nav>
        <div className='text-center p-10'>
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Achille Cannavale</h2>
          <h3 className='tet-2xl py-2 md:text-3xl dark:text-gray-300'>CS Engineering Student | Developer</h3>
          <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-100'>
          I'm a Computer Science Engineering student based in Italy. I have a profound interest in Full Stack Development, Machine and Deep Learning, and Cyber Security.
          </p>
        </div>
        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
        <AiFillLinkedin></AiFillLinkedin>
          <AiFillTwitterCircle></AiFillTwitterCircle>
          <AiFillYoutube></AiFillYoutube>
        </div>
        <div className='relative mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden '>
          <Image src={deved} layout="fill" objectFit="cover"></Image>
        </div>
        </section>
        <section>
          <div className=''>
            <h3 className='text-3xl py-1'>About Me</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
            I am particular interest in the world of software development and artificial intelligence.
            I have recently started to independently study the development on the Unity game engine, and above all the development of multi-platform mobile applications through the Flutter framework.
            </p>
          </div>
          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-500'>
              <h3 className='text-lg font-medium pt-8 pb-2'>PeggleBox2D</h3>
              <p className='py-2'>PeggleBox2D is an University Project which consists of the clone of the Peggle game, made with Qt and the Box2D library.</p>
              <p className='text-gray-800 py-1'>C++</p>
              <p className='text-gray-800 py-1'>C++</p>
              <p className='text-gray-800 py-1'>C++</p>
              <p className='text-gray-800 py-1'>C++</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <h3 className='text-lg font-medium pt-8 pb-2'>PeggleBox2D</h3>
              <p className='py-2'>PeggleBox2D is an University Project which consists of the clone of the Peggle game, made with Qt and the Box2D library.</p>
              <p className='text-gray-800 py-1'>C++</p>
              <p className='text-gray-800 py-1'>C++</p>
              <p className='text-gray-800 py-1'>C++</p>
              <p className='text-gray-800 py-1'>C++</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <h3 className='text-lg font-medium pt-8 pb-2'>PeggleBox2D</h3>
              <p className='py-2'>PeggleBox2D is an University Project which consists of the clone of the Peggle game, made with Qt and the Box2D library.</p>
              <p className='text-gray-800 py-1'>C++</p>
              <p className='text-gray-800 py-1'>C++</p>
              <p className='text-gray-800 py-1'>C++</p>
              <p className='text-gray-800 py-1'>C++</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <h3 className='text-lg font-medium pt-8 pb-2'>PeggleBox2D</h3>
              <p className='py-2'>PeggleBox2D is an University Project which consists of the clone of the Peggle game, made with Qt and the Box2D library.</p>
              <p className='text-gray-800 py-1'>C++</p>
              <p className='text-gray-800 py-1'>C++</p>
              <p className='text-gray-800 py-1'>C++</p>
              <p className='text-gray-800 py-1'>C++</p>
            </div>
          </div>
        </section>
        <footer className='text-center'>Built and designed by Me.
All rights reserved. ©</footer>
      </main>
    </div>
  )
}
